# How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?

import math


def no_math_solution(maxA: int, maxB: int):
    s = set(a**b for a in range(2, maxA + 1) for b in range(2, maxB + 1))
    return len(s)


if __name__ == "__main__":
    # a, b = map(int, input().split())
    a, b = 100, 100
    print(no_math_solution(a, b))
